solrfacets/config/routes.rb
Solrfacets::Application.routes.draw do
  get 'search' => 'search#search', :as => 'search'

  resources :projects

end

solrfacets/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :repository_url, :title, :tag_list
  acts_as_taggable_on :tags

  searchable :auto_index => true, :auto_remove => true do
    string :title, :stored => true
    text :description, :stored => true
    string :tag_list, :multiple => true, :stored => true
  end
end

solrfacets/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

solrfacets/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

solrfacets/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    # only search if keywords exist
    if params[ :keywords ].nil? || params[ :keywords ].empty?
      @hits = [ ]
    else
      @search = Project.search do
        fulltext params[ :keywords ] do
          highlight :description
        end

        facet :tag_list
        paginate :per_page => 10

        # tags, AND'd
        if params[ :tag ].present?
          all_of do
            params[ :tag ].each do |tag|
              with( :tag_list, tag )
            end
          end
        end
        

      end
      @hits = @search.hits

    end
  end
end

solrfacets/app/helpers/application_helper.rb
module ApplicationHelper
end

solrfacets/app/helpers/projects_helper.rb
module ProjectsHelper
end

solrfacets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Solrfacets</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

solrfacets/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :repository_url %><br />
    <%= f.text_field :repository_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

solrfacets/app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

solrfacets/app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Repository url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.description %></td>
    <td><%= project.repository_url %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

solrfacets/app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

solrfacets/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Repository url:</b>
  <%= @project.repository_url %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

solrfacets/app/views/search/search.html.erb
<h1>Search#search</h1>

<%= form_tag search_path, { method: :get } do %>
  <%= text_field_tag :keywords, params[ :keywords ] %>
  <%= submit_tag 'Search', { name: nil } %>
<% end %>

<% if @hits.any? %>
  <h2>Search Results</h2>
  <ul>
    <% @hits.each do |hit| %>
      <li>
      <%= link_to hit.stored( :title ), project_path( hit.primary_key ) %><br>
      <% hit.highlights( :description ).each do |highlight| %>
        <%= highlight.format { |word| "*#{word}*" } %>
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<%
  facets_html = ''
  if not @search.nil?
  
    # check for existing tags in query string
    existing_tag_facets = [ ]
    if params[ :tag ].present?
      existing_tag_facets = params[ :tag ]
    end

    facet_links_off = ''
    facet_links_on = ''

    @search.facet( :tag_list ).rows.each_with_index do |facet, index|
      break if index == 10;

      # check if facet is selected
      if ( params[ :tag ].kind_of?( Array ) and params[ :tag ].include? facet.value )
        tag_facets = existing_tag_facets - [ facet.value ]

        facet_links_on << "<li>#{link_to facet.value, { keywords: params[ :keywords ], tag: tag_facets }} (-)</li>"
      else
        tag_facets = existing_tag_facets + [ facet.value ]
        
        facet_links_off << "<li>#{link_to facet.value, { keywords: params[ :keywords ], tag: tag_facets}} (#{facet.count})</li>"
      end
    end

    facets_html << '<b>Filter by tags</b>'
    if facet_links_on.size > 0
      facets_html << "<ul class='search_facets_on'>#{facet_links_on}</ul>"
    end
    if facet_links_off.size > 0
      facets_html << "<ul class='search_facets_off'>#{facet_links_off}</ul>"
    end

  end
%>
<%= raw facets_html %>